name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 15 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
   # permissions:
   #   contents: read/write 
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "scgao94@gmail.com"
          git config --local user.name "DemonGao"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "为绿而绿！"
          git push
